project:
  type: website
  output-dir: docs

website:
  title: "Charaf's Blog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
    right:
      - icon: github
        href: https://github.com/eddcben
        aria-label: GitHub

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    smooth-scroll: true
    html-math-method: katex
    mermaid:
      theme: default
